base_url = "https://velodex.readthedocs.io"
title = "velodex"
description = "A read-through cache and private registry for PyPI and Docker, in one fast Rust binary."
compile_sass = true
build_search_index = false
generate_feeds = false

[markdown]
highlighting = { theme = "ayu-dark" }

[extra]
repo = "https://github.com/tox-dev/velodex"
