base_url = "https://velodex.readthedocs.io"
title = "velodex"
description = "A PyPI-compatible read-through cache and private index, written in Rust."
compile_sass = true
build_search_index = false
generate_feeds = false

[markdown]
highlighting = { theme = "ayu-dark" }

[extra]
repo = "https://github.com/tox-dev/velodex"
